apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: art-autoscale-cpu
  namespace: default
spec:
  maxReplicas: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: art-deployment
  targetCPUUtilizationPercentage: 80