apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: art-autoscale-memory
  namespace: default
spec:
  maxReplicas: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: art-deployment
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80