kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkinsworkspace
  namespace: jenkins
  annotations:
    volume.beta.kubernetes.io/storage-class: efs
spec:
  storageClassName: efs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

