apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-config
  namespace: kube-system
data:
  config.json: |-
    {
      "credHelpers": {
        "421093829873.dkr.ecr.us-east-1.amazonaws.com": "ecr-login"
      }
    }
